### ISSUE TITLE
Support for .vue files

### ISSUE THREAD

**Issue by TeNNoX** [eramdam/fold-imports#4]
The extension currently doesn't support .vue files. Could you adapt it?

Thanks in any case :)

```vue
<template>
    ...
</template>

<script lang="ts">
import Vue from 'vue'
import TodosClassComponent from 'components/ClassComponent.vue'
...
```

**Comment by TeNNoX** [comment]
I just found the option `extraLanguages`, and tried it:
```js
"fold-imports.extraLanguages": [
  "vue"
]
```

But it doesn't work. I didn't easily figure out how to debug an extension, otherwise I'd give more info.

**Comment by eramdam** [comment]
Hum, I never really used Vue but as long VSCode is capable of folding the import blocks I guess it should be possible. Does VScode show the folding indicator near the imports in your file?

<img width="321" alt="image" src="https://user-images.githubusercontent.com/1409924/83364327-77762300-a355-11ea-9de2-01ed6397437e.png">

**Comment by TeNNoX** [comment]
![Screenshot from 2020-06-05 09-47-40](https://user-images.githubusercontent.com/2084639/83856566-a99ad280-a711-11ea-9213-be188fa74eeb.png)

It does.

**Comment by eramdam** [comment]
Okay, I'll try to figure it out. Do you have a sample Vue project I could use as a testbench?

**Comment by TeNNoX** [comment]
https://github.com/prograhammer/vue-pizza/blob/master/src/layouts/default/main.vue :shrug:

**Comment by eramdam** [comment]
Okay so after looking at the project. I've noticed that VSCode only supports folding the destructured imports, not the import blocks itself.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/1409924/83957359-b48e5980-a81c-11ea-83c5-d41bfdfccc21.png">

Which means that triggering a fold action at the line of the first import will at best do nothing or at worst, fold the entire `script` tag because that's the closest region that VSCode knows how to fold.

So I guess there's not a good way to fix it. My guess is that to fix this we'd need to implement a [folding ranger provider](https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider) to properly fold the imports block and not just an object or the script tag. I have no idea how involved that is and that would be a bit out of scope for this extension (and I would be surprised if nobody implemented that already 🤔 )

**Comment by TeNNoX** [comment]
Thanks for giving it a shot :)
